### ISSUE TITLE
difference with jazzsaxmafia/show_attend_and_tell.tensorflow 

### ISSUE THREAD

**Issue by joyousrabbit** [yunjey/show-attend-and-tell-tensorflow#10]
hello, Im newbie about LSTM and NLP. Is your implementation better than jazzsaxmafia/show_attend_and_tell.tensorflow ? which one should I take for first study?

Hope reply and many tnanks.

**Comment by yunjey** [comment]
Both codes are fine. However, there are some bugs in jazzsaxmafia's code. Additionally, in my code, you can check pretty good attention results.

**Comment by joyousrabbit** [comment]
@yunjey yes i see thank you.
