### ISSUE TITLE
Memoryerror in prepro.py

### ISSUE THREAD

**Issue by linrio** [yunjey/show-attend-and-tell-tensorflow#14]
```
Loaded ./data/train/train.annotations.pkl..
Traceback (most recent call last):
  File "prepro.py", line 212, in <module>
    main()
  File "prepro.py", line 195, in main
    all_feats = np.ndarray([n_examples, 196, 512], dtype=np.float32)
MemoryError

```

How to reduce to number of training dataset?

**Comment by xieqiangqiang** [comment]
I faced tha same proplem in running train.py.  The number of trainning dataset is so huge, so the extracted train_features.hkl  is 33.2GB. The memory of my pc is 32GB, but it happened. I think there are two solutions: reducing the number of trainning dataset or setting a queue in loadding the train.features.hkl.

waitting for the solution....

**Comment by brb-chen** [comment]
get same problem, waiting for solution

**Comment by yunjey** [comment]
I recommend to use more than 40GB RAM for running this code. 

[Other project](https://github.com/yunjey/knowing-when-to-look) which is very similar to this project will deal with this problem. I am working on progress.

**Comment by forthtemple** [comment]
If you're using Linux you can create a 40G swap file like in https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04 and it preprocesses but is very slow.  But once preprocesed and started training, its still gave me a memory error
