### ISSUE TITLE
 Can not extract features with vggnet

### ISSUE THREAD

**Issue by kilickaya** [yunjey/show-attend-and-tell-tensorflow#2]
While trying to extract features, I came across these errors: 

1. When I set the batch_size to 100:

Traceback (most recent call last):
  File "prepare_features.py", line 53, in <module>
    main(sys.argv[1:])
  File "prepare_features.py", line 40, in main
    imread(x, mode='RGB'), image_batch_file)).astype(np.float32)  
ValueError: setting an array element with a sequence

2. When I set the batch_size to 1 due to the above error: 

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv1_1/w
	 [[Node: conv1_1/w/read = Identity[T=DT_FLOAT, _class=["loc:@conv1_1/w"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_1/w)]]
	 [[Node: conv5_3/BiasAdd/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_9_conv5_3/BiasAdd", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by yunjey** [comment]
sorry, i will update it soon.

**Comment by yunjey** [comment]
I updated vggnet.py. Now, it will works.
