### ISSUE TITLE
which version of tf in your env?

### ISSUE THREAD

**Issue by brb-chen** [yunjey/show-attend-and-tell-tensorflow#20]
my env is tf 1.0.0, and with so much variable sharing problems,
i change the code with variable scope, but it still can't work...

Error Info looks like:
     ValueError: Variable lstm/basic_lstm_cell/weights already exists? ....

Otherwise, 
     tf.get_variable_scope().reuse_variables() lies in Line 78 of solver.py, it change the whole variable scope to reuse status, is that what you desire?

Thks!

**Comment by yunjey** [comment]
I recommend using TensorFlow 0.11 version to run this project's code. I will upgrade the version of the code layer, but not sooner.
