### ISSUE TITLE
Evaluate error

### ISSUE THREAD

**Issue by peterWon** [yunjey/show-attend-and-tell-tensorflow#5]
Hello, yunjey, thanks a lot for your nice work!  I got a problem when I run 'train.py', at the line of 'scores = evaluate(data_path='./data', split='val', get_scores=True)', raised a error like this: 
![default](https://cloud.githubusercontent.com/assets/20137676/20828170/13886494-b8b1-11e6-90b9-1353d19d1613.png)
I'm new to this field, I'll very appreciate it if you can give some advice. Thank you!

**Comment by yunjey** [comment]
Did you change the file storage path?
For evaluation, you need to have data/val/val.references.pkl and data/val/val.candidate.captions.pkl.

**Comment by peterWon** [comment]
I just checked,they are both there.
What makes me confused is that I have set the parameter of self.print_bleu = kwargs.pop('print_bleu', False) as default, but it still ran into that evaluate part .

**Comment by peterWon** [comment]
I find that  the first step is to copy the project-coco-caption,I just coped the file folder 'pycocoevalcap' to the path ./core, is that work or is this where the problem is?

**Comment by yunjey** [comment]
You have to clone pycocoevalcap and this repo(show-attend-and-tell-tensorflow) in same directory.

**Comment by InaKhandelwal** [comment]
I have cloned the repositories as mentioned but still I am facing the above error. What can be the problem?
