### ISSUE TITLE
generate captions for an image or multi-images?

### ISSUE THREAD

**Issue by xieqiangqiang** [yunjey/show-attend-and-tell-tensorflow#7]
Firstly, i appreciate you for your code, and i am a novice.  when i trained a model, i is thinking how can i  use it to test a image. so i think maybe you have this code.

**Comment by yunjey** [comment]
This code is based on MSCOCO dataset. If you want to test your custom image, you should resize the image to 224x224 as well as fix the 196th and 197th lines in solver.py.

**Comment by alexandercameronh** [comment]
Can you copy and paste the segment of code that needs to be changed and let us know what it should be changed to in order to test our own custom images? I've changed some code in solver.py so my line numbers do not match up to yours.

**Comment by saranshvora** [comment]
@alexandercameronh Hi, I am also using this model to test my own images. Have you found a solution for the same ? If yes, can you please share it ? 
Thank You
